---
title: "Diversidad_Hill_Tax"
author: "Nastienka Yael Perez Jimenez"
date: "2024-03-21"
output: html_document
---

```{r}
library(tidyverse)
library(iNEXT)
library(entropart)
```


```{r}
mur_tax <- read.csv("mur_df.csv", header = TRUE)
View(mur_tax)
```

# Sample Coverage

## Region 1

```{r}
mur_tax_mer <- mur_tax[, 1:4]
mur_tax_mer <- subset(mur_tax_mer, rowSums(mur_tax_mer != 0) > 0)
View(mur_tax_mer)

MC_mur_tax_mer <- MetaCommunity(mur_tax_mer)

MC_mur_tax_mer$Nsi
MC_mur_tax_mer$N
MC_mur_tax_mer$Nspecies
MC_mur_tax_mer$Ni
MC_mur_tax_mer$SampleCoverage
MC_mur_tax_mer$SampleCoverage.communities
```

## Region 2
```{r}
mur_tax_tiz <- mur_tax[, 5:7]
mur_tax_tiz <- subset(mur_tax_tiz, rowSums(mur_tax_tiz != 0) > 0)
View(mur_tax_tiz)

MC_mur_tax_tiz <- MetaCommunity(mur_tax_tiz)

MC_mur_tax_tiz$Nsi
MC_mur_tax_tiz$N
MC_mur_tax_tiz$Nspecies
MC_mur_tax_tiz$Ni
MC_mur_tax_tiz$SampleCoverage
MC_mur_tax_tiz$SampleCoverage.communities
```

## Region 3


#.
### Calakmul

```{r}
mur_tax_cal <- mur_tax[, 8:10]
mur_tax_cal <- subset(mur_tax_cal, rowSums(mur_tax_cal != 0) > 0)
View(mur_tax_cal)

MC_mur_tax_cal <- MetaCommunity(mur_tax_cal)

MC_mur_tax_cal$Nsi
MC_mur_tax_cal$N
MC_mur_tax_cal$Nspecies
MC_mur_tax_cal$Ni
MC_mur_tax_cal$SampleCoverage
MC_mur_tax_cal$SampleCoverage.communities
```


